import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
// import "./globals.css";

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavbarBrand from 'react-bootstrap/NavbarBrand'
import NavbarToggle from 'react-bootstrap/NavbarToggle'
import NavbarCollapse from 'react-bootstrap/NavbarCollapse'
import NavLink from "react-bootstrap/NavLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <Navbar expand="lg" className="bg-body-tertiary">
          <Container>
            <NavbarBrand href="/">Platform-Name</NavbarBrand>
            <NavbarToggle></NavbarToggle>
            <NavbarCollapse>
            </NavbarCollapse>
          </Container>
        </Navbar>
        <Container>
          <Row>
            {children}
          </Row>
        </Container>
      </body>
    </html>
  );
}
