name: '0.1'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER="mama_bear"
      - MYSQL_PASSWORD="password"
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./backend
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    command: bash -c "
      npx sequelize db:migrate:undo:all && 
      npx sequelize db:migrate && 
      npx sequelize db:seed:all --debug && 
      node app.js"
  frontend:
    depends_on:
      - backend
    build: ./frontend
    env_file:
      - ./.env
    environment:
      - BACKEND_TARGET="http://localhost:5001/"
    ports:
      - $NEXTJS_LOCAL_PORT:$NEXTJS_DOCKER_PORT
volumes: 
  db: